baseURL = 'https://ericstiens.dev'
languageCode = 'en-US'
title = 'eric stiens dot dev'

disableKinds = ['taxonomy', 'term']

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.115.0"
[[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/alpinejs"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
